# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: 3D Face Modelling
author: Rohan Tuli
logo: logo.png
copyright: '2023'
exclude_patterns : [README.md]

execute:
  execute_notebooks: force

latex:
  latex_documents:
    targetname: book.tex

repository:
  url: https://github.com/rohantuli7/3dmodelling.io.git 
  path_to_book: docs  
  branch: main  

html:
  use_issues_button: false
  use_repository_button: false
